devUrl=https://benepik.org/pwa/bpcpkiran/#/lamwv

browser=chrome
pageLoad.timeout.seconds=60
download.dir=/home/chinmay/Downloads

log.username=chinmay.srivastava@benepik.com
log.password=Abcde@1234

loginUsername=hello@benepik.com
loginPassword=Abcde@1234

headless=false

# Database Configuration UAT
db.url=jdbc:mysql://mysql5uatenvironmentauroradatabase-cluster.cluster-co15eactbazy.ap-south-1.rds.amazonaws.com:3306/benepik_plus
db.username=chinmay
db.password=chinmay@2002
db.adminId=1058

# Database Configuration DEV
#db.url=jdbc:mysql://mysql5developmentenvironmentauroradatabase-cluster.cluster-co15eactbazy.ap-south-1.rds.amazonaws.com:3306/benepik_plus
#db.username=chinmay
#db.password=chinmay&%^$5$
#db.adminId=2221

# OTP Configuration
otp.manual.timeout.seconds=120
otp.cooldown.toast.timeout.seconds=2
otp.cooldown.retry.sleep.ms=60000
otp.auto.retry.attempts=2
